#!/usr/bin/make

MTHOME ?= $(HOME)/mosesmake

### REQUIRED VARIABLES ###
#factors = factorless pos pos-gen lemma+pos+morph surface+lemma+pos+morph
factors = pos
src = ja
tgt = en
min = 0
max = 40
corpus = test2007
lm_corpus = test2007
recaser_corpus = test2007
recaser_root = $(MTHOME)/test/recaser
recaser_dir = $(recaser_root)/$(tgt)/$(lm_corpus)

### REQUIRED FILES ###

train_src_file = $(MTHOME)/test/data/$(corpus)/train.$(src).txt
train_tgt_file = $(MTHOME)/test/data/$(corpus)/train.$(tgt).txt
dev_src_file = $(MTHOME)/test/data/$(corpus)/dev.$(src).txt
dev_tgt_file = $(MTHOME)/test/data/$(corpus)/dev.$(tgt).txt
test_src_file = $(MTHOME)/test/data/$(corpus)/test.$(src).txt
test_tgt_file = $(MTHOME)/test/data/$(corpus)/test.$(tgt).txt
lm_file = $(MTHOME)/test/data/$(corpus)/train.$(tgt).txt
recaser_file = $(MTHOME)/test/data/$(corpus)/train.$(tgt).txt

### OPTIONAL ###
# comment out to disable evaluation. baseline(s) required only for significance testing
#evaluation = bleu significance meteor
samplen = 100
#baseline_mert =
#baseline_no_mert =
