#!/usr/bin/make

include ../Makefile.vars

all:	$(lm_corpus).fact.lc.tok.lm $(lm_corpus).fact.lc.pos.lm

nuke:	clean
	rm -f *.lm

%.tok.lm:	%.tok
	moses_srilm_kn $< $@

%.pos.lm:	%.pos
	moses_srilm_wb $< $@

$(lm_corpus):	$(lm_file)
	cp -f $< $@

include $(MHOME)/makefiles/Makefile.fact

.PHONY:	all nuke
