#!/usr/bin/make

include ../Makefile.vars
inclue $MHOME/makefiles/Makefile.fact

all:	clean $(corpus).train.pos.$(src) $(corpus).train.tok.$(src) \
			  $(corpus).train.pos.$(tgt) $(corpus).train.tok.$(tgt)

.PHONY:	all
