#!/usr/bin/make

include ../Makefile.vars

all:	$(lm_corpus).surface.lm $(lm_corpus).pos.lm

nuke:	clean
	rm -f *.lm

%.surface.lm:	%.tok.$(tgt)
	moses_srilm_kn $< $@
	
%.pos.lm:	%.tok.$(tgt)
	moses_srilm_wb $< $@

$(lm_corpus).clean.$(tgt):	$(lm_corpus)
	ln -sf $< $@

$(lm_corpus):	$(lm_file)
	cp -f $(lm_file) $(lm_corpus)

include $(MHOME)/makefiles/Makefile.fact

.PHONY:	all nuke
