#!/usr/bin/make

include Makefile.vars

all:	corpus lm

%:	$MHOME/makefiles/Makefile.%
	mkdir -p $*
	cp -f $MHOME/makefiles/Makefile.$* $*/Makefile
	make -C $*

nuke:
	rm -rf corpus lm

.PHONY: all clean nuke
