#!/usr/bin/make

include Makefile.vars

all:	corpus

%:	$MHOME/makefiles/Makefile.%
	mkdir -p $*
	cp $MHOME/makefiles/Makefile.$* $*/Makefile
	cd $* && make

nuke:
	rm -rf corpus

.PHONY: all clean nuke
