#!/usr/bin/make

### REQUIRED VARIABLES ###
#factors = factorless pos pos-gen lemma+pos+morph tok+lemma+pos+morph
factors = char
src = en
tgt = kt
min = 0
max = 40
corpus = wiki-trans
lm_corpus = wiki-trans
recaser_corpus = wiki-trans
recaser_root = $(HOME)/moses/recaser
recaser_dir = $(recaser_root)/$(tgt)/$(lm_corpus)

### REQUIRED FILES ###

train_src_file = /path/to/english/place/names/train
train_tgt_file = /path/to/katakana/place/names/train
dev_src_file = /path/to/english/place/names/dev
dev_tgt_file =  /path/to/katakana/place/names/dev
test_src_file = /path/to/english/place/names/test
test_tgt_file = /path/to/katakana/place/names/test
lm_file = /path/to/katakana/place/names/train
recaser_file = /path/to/katakana/place/names/train

### OPTIONAL ###
# comment out to disable evaluation. baseline(s) required only for significance testing
#evaluation = bleu significance meteor
samples=100
#baseline_mert = /path/to/baseline/mert/translations
#baseline_no_mert = /path/to/basenline/no/mert/translations
